name: Run unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop, main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
